#### Import libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

#### Load the data

In [2]:
data = pd.read_csv('1.02. Multiple linear regression.csv')

In [3]:
data.head()

SAT   GPA  Rand 1,2,3
0  1714  2.40           1
1  1664  2.52           3
2  1760  2.54           3
3  1685  2.74           3
4  1693  2.83           2

In [4]:
data.describe()

SAT        GPA  Rand 1,2,3
count    84.000000  84.000000   84.000000
mean   1845.273810   3.330238    2.059524
std     104.530661   0.271617    0.855192
min    1634.000000   2.400000    1.000000
25%    1772.000000   3.190000    1.000000
50%    1846.000000   3.380000    2.000000
75%    1934.000000   3.502500    3.000000
max    2050.000000   3.810000    3.000000

### Create multiple linear regression

#### Declare the variables

In [5]:
y = data['GPA']
x = data[['SAT', 'Rand 1,2,3']]

#### Standardization

In [6]:
from sklearn.preprocessing import StandardScaler

In [8]:
scaler = StandardScaler()

In [9]:
scaler.fit(x)

/home/sonia/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:645: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)


StandardScaler(copy=True, with_mean=True, with_std=True)

In [10]:
x_scaled = scaler.transform(x)

/home/sonia/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  """Entry point for launching an IPython kernel.


In [11]:
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

#### Regression with scaled features

In [12]:
reg = LinearRegression()
reg.fit(x_scaled, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [13]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [14]:
reg.intercept_

3.330238095238095

#### Creating a summary table

In [18]:
reg_summary = pd.DataFrame([['Bias'], ['SAT'], ['Rand 1,2,3']], columns=['Features'])
reg_summary['weights'] = reg.intercept_, reg.coef_[0], reg.coef_[1]

In [19]:
reg_summary

Features   weights
0        Bias  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

#### Make predictions with the standard coefficients (weights)

In [20]:
new_data = pd.DataFrame(data=[[1700,2],[1800,1]], columns = ['SAT', 'Rand 1,2,3'])
new_data

SAT  Rand 1,2,3
0  1700           2
1  1800           1

In [21]:
reg.predict(new_data)

array([295.39979563, 312.58821497])

In [22]:
new_data_scaled = scaler.transform(new_data)
new_data_scaled

/home/sonia/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  """Entry point for launching an IPython kernel.


array([[-1.39811928, -0.07002087],
       [-0.43571643, -1.24637147]])

In [23]:
reg.predict(new_data_scaled)

array([3.09051403, 3.26413803])

#### What if we removed the 'Random 1,2,3' variable?

In [26]:
reg_simple = LinearRegression()
x_simple_matrix = x_scaled[:,0].reshape(-1,1)
reg_simple.fit(x_simple_matrix, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [28]:
reg_simple.predict(new_data_scaled[:,0].reshape(-1,1))

array([3.08970998, 3.25527879])

## Avoid overfitting

### Train test split

In [29]:
import numpy as np
from sklearn.model_selection import train_test_split

In [30]:
a = np.arange(1,101)

In [31]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [32]:
b = np.arange(501, 601)

In [33]:
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

### Split the data

In [34]:
train_test_split(a)

[array([12, 69, 84, 77, 72, 67, 26, 17, 22, 31, 61, 49, 83, 43, 68, 33,  2,
        18, 47, 63, 97, 87, 88, 93, 65, 66, 16, 40, 45, 64, 73, 85, 27, 81,
        99, 19,  6, 28, 30, 60, 92, 89, 57, 10, 32, 25, 24, 41,  7, 58, 53,
        29, 71, 48,  9, 95, 13, 20, 80,  3, 86, 82, 23,  1, 59, 56, 35, 44,
        21, 76, 55, 96, 52, 75, 39]),
 array([ 50,  42,  34,  94,  46,  38,  62,  37,   8,  78,  36,  51,  14,
         70, 100,  11,   4,  91,  54,   5,  98,  74,  15,  90,  79])]

In [52]:
a_train, a_test, b_train, b_test = train_test_split(a, b, test_size = 0.2, random_state=336)

In [49]:
a_train

array([ 61,  38,   3,  39,  60,  85,  30,  34,  93,  27,  31,  58,  54,
        22,  63,   9,  76,  45,  21,  35,  90,  97,  16,  18,  64,  23,
        24,  74,  92,  98,  88,  32,  37,  99,  51,  12,  19,  70,  47,
        25,   4,  10,  65,  42,  33,  15,  81,   7,   1,  56,  13,  86,
        46,  73, 100,  28,  95,  67,  83,  44,  77,  66,  71,  96,  29,
        59,  82,  62,  75,  26,  78,  50,  43,  55,  53,  11,  36,  94,
        91,  41])

In [50]:
a_test

array([ 2, 14, 17, 80,  6, 57, 48, 87, 68, 49, 79, 84, 72, 20,  8, 52, 89,
        5, 40, 69])

### Explore the result

In [51]:
a_train.shape, a_test.shape

((80,), (20,))

In [53]:
b_train.shape, b_test.shape

((80,), (20,))

In [54]:
b_train

array([542, 598, 581, 583, 537, 509, 541, 527, 543, 575, 552, 556, 511,
       567, 507, 517, 551, 596, 518, 534, 544, 547, 564, 580, 554, 594,
       525, 571, 538, 508, 512, 524, 600, 592, 563, 505, 533, 528, 582,
       557, 540, 545, 562, 589, 590, 546, 514, 577, 504, 526, 593, 516,
       585, 548, 584, 558, 573, 549, 561, 588, 565, 587, 570, 591, 553,
       530, 579, 599, 535, 522, 523, 560, 515, 559, 569, 501, 574, 572,
       529, 536])

In [55]:
b_test

array([566, 576, 586, 519, 521, 513, 502, 539, 531, 550, 597, 520, 503,
       595, 578, 568, 532, 506, 555, 510])